CREATE TABLE summary (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    in_total INT NOT NULL DEFAULT 0,
    out_total INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY uq_summary_date (date)
);