services:
  mysql:
    image: mysql:8.0
    container_name: devicemap-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devicemap
      MYSQL_DATABASE: devicemap
      MYSQL_USER: devicemap
      MYSQL_PASSWORD: devicemap
    ports:
      - "3306:3306"
    volumes:
      - ./devicemap/mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-udevicemap", "-pdevicemap"]
      interval: 10s
      timeout: 10s
      retries: 60
      start_period: 300s
    networks:
      - devicemap-net

  nginx:
      build:
        context: .
        dockerfile: nginx/Dockerfile
      container_name: devicemap-nginx
      restart: always
      ports:
        - "80:80"
      depends_on:
        - backend
        - mediamtx
      networks:
        - devicemap-net
  backend:
    build:
      context: ./backend
    container_name: devicemap-backend
    restart: always
    env_file:
      - ./backend/.env.production
    environment:
      - PLANE_IMAGE_DIR=/app/image/planes
      - IMAGE_ROOT_DIR=/app/image
      - DEVICE_ICON_DIR=/app/image/icon
      - USER_AVATAR_DIR=/app/image/user
    expose:
      - "3000"
    volumes:
      - ./uploads:/app/uploads
      - ./devicemap/image/planes:/app/image/planes
      - ./devicemap/image/icon:/app/image/icon
      - ./devicemap/image/user:/app/image/user
    depends_on:
      mediamtx:
          condition: service_started
      mysql:
          condition: service_healthy
    networks:
      - devicemap-net

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: devicemap-mediamtx
    restart: always
    ports:
      - "8554:8554"       #RTSP
      - "8189:8189/udp"   #WebRTC UDP
    expose:
      - "8888"
      - "8889"
      - "9997"
    volumes:
      - ./mediamtx_record:/recordings
      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro
    networks:
      - devicemap-net

networks:
  devicemap-net:
    driver: bridge