DROP TABLE IF EXISTS `reports`;

CREATE TABLE `reports` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `time_start` varchar(15) NOT NULL,
  `time_end` varchar(15) NOT NULL,
  `device_id` char(5) DEFAULT NULL,
  `device_name` varchar(255) DEFAULT NULL,
  `device_type_id` char(5) DEFAULT NULL,
  `device_type_name` varchar(255) DEFAULT NULL,
  `plane_id` char(5) DEFAULT NULL,
  `plane_name` varchar(255) DEFAULT NULL,
  `state` tinyint unsigned NOT NULL DEFAULT '0',
  `user_id` bigint unsigned DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `user_full_name` varchar(255) DEFAULT NULL,
  `confirmed_by_id` bigint unsigned DEFAULT NULL,
  `confirmed_by_name` varchar(255) DEFAULT NULL,
  `confirmed_at` datetime DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_reports_device_id` (`device_id`),
  KEY `idx_reports_plane_id` (`plane_id`),
  KEY `idx_reports_user_id` (`user_id`),
  KEY `idx_reports_state` (`state`),
  KEY `idx_reports_confirmed_by` (`confirmed_by_id`),
  CONSTRAINT `fk_reports_confirmed_by` FOREIGN KEY (`confirmed_by_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_reports_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_reports_plane` FOREIGN KEY (`plane_id`) REFERENCES `planes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_reports_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_reports_state` CHECK ((`state` in (0,1,2)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;